# Generated by Django 3.0 on 2020-01-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_auto_20200107_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
