# Generated by Django 3.0 on 2020-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_remove_companyprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='application_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_status',
            field=models.CharField(choices=[('---------', '---------'), ('Draft', 'Draft'), ('publish', 'Publish')], max_length=100),
        ),
    ]
