# Generated by Django 3.0 on 2020-01-09 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_auto_20200107_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
