# Generated by Django 3.0 on 2020-01-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_jobpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='application_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
