# Generated by Django 3.0 on 2020-01-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_jobpost_application_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_status',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
