# Generated by Django 3.0 on 2020-01-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_companyprofile_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='counter',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
