# Generated by Django 3.0 on 2020-01-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_auto_20200121_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='counter',
        ),
    ]
