# Generated by Django 3.0.2 on 2020-02-01 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_remove_jobpost_counter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProfile',
        ),
    ]
