# Generated by Django 3.0.2 on 2020-02-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0013_auto_20200201_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
