# Generated by Django 3.0 on 2020-01-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200109_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('---------', '---------'), ('is_employer', 'Employer'), ('is_freelancer', 'Freelancer/Applicant')], default='', max_length=100),
        ),
    ]
