# Generated by Django 3.0 on 2020-01-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200110_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('---------', '---------'), ('is_employer', 'Employer'), ('is_freelancer', 'Freelancer/Applicant')], default=None, max_length=100),
        ),
    ]
