# Generated by Django 3.0 on 2020-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200110_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eko_atlantic',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='ikoy',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='user',
            name='lekki',
            field=models.NullBooleanField(),
        ),
    ]
