# Generated by Django 3.0 on 2020-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200120_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eko_atlantic',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='ikoy',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='lekki',
            field=models.NullBooleanField(),
        ),
    ]
