# Generated by Django 3.0 on 2020-01-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200120_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ikoy',
            new_name='ikoyi',
        ),
    ]
