# Generated by Django 3.0 on 2020-01-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200120_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eko_atlantic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ikoyi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='lekki',
            field=models.BooleanField(default=False),
        ),
    ]
