# Generated by Django 3.0.2 on 2020-01-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20200125_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='publish_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
